// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: Election.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Election_Type int32

const (
	Election_EXPLORER Election_Type = 0
	Election_ECHO     Election_Type = 1
)

// Enum value maps for Election_Type.
var (
	Election_Type_name = map[int32]string{
		0: "EXPLORER",
		1: "ECHO",
	}
	Election_Type_value = map[string]int32{
		"EXPLORER": 0,
		"ECHO":     1,
	}
)

func (x Election_Type) Enum() *Election_Type {
	p := new(Election_Type)
	*p = x
	return p
}

func (x Election_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Election_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Election_proto_enumTypes[0].Descriptor()
}

func (Election_Type) Type() protoreflect.EnumType {
	return &file_Election_proto_enumTypes[0]
}

func (x Election_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Election_Type.Descriptor instead.
func (Election_Type) EnumDescriptor() ([]byte, []int) {
	return file_Election_proto_rawDescGZIP(), []int{0, 0}
}

type Election struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Election_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ueb02.Election_Type" json:"type,omitempty"`
	Initiator string        `protobuf:"bytes,2,opt,name=initiator,proto3" json:"initiator,omitempty"`
}

func (x *Election) Reset() {
	*x = Election{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Election_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Election) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Election) ProtoMessage() {}

func (x *Election) ProtoReflect() protoreflect.Message {
	mi := &file_Election_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Election.ProtoReflect.Descriptor instead.
func (*Election) Descriptor() ([]byte, []int) {
	return file_Election_proto_rawDescGZIP(), []int{0}
}

func (x *Election) GetType() Election_Type {
	if x != nil {
		return x.Type
	}
	return Election_EXPLORER
}

func (x *Election) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

var File_Election_proto protoreflect.FileDescriptor

var file_Election_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x75, 0x65, 0x62, 0x30, 0x32, 0x22, 0x72, 0x0a, 0x08, 0x45, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x75, 0x65, 0x62, 0x30, 0x32, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x1e, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x58, 0x50, 0x4c, 0x4f, 0x52, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x65, 0x6c, 0x73, 0x63,
	0x68, 0x2f, 0x76, 0x61, 0x61, 0x2f, 0x75, 0x65, 0x62, 0x30, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Election_proto_rawDescOnce sync.Once
	file_Election_proto_rawDescData = file_Election_proto_rawDesc
)

func file_Election_proto_rawDescGZIP() []byte {
	file_Election_proto_rawDescOnce.Do(func() {
		file_Election_proto_rawDescData = protoimpl.X.CompressGZIP(file_Election_proto_rawDescData)
	})
	return file_Election_proto_rawDescData
}

var file_Election_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Election_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Election_proto_goTypes = []interface{}{
	(Election_Type)(0), // 0: ueb02.Election.Type
	(*Election)(nil),   // 1: ueb02.Election
}
var file_Election_proto_depIdxs = []int32{
	0, // 0: ueb02.Election.type:type_name -> ueb02.Election.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Election_proto_init() }
func file_Election_proto_init() {
	if File_Election_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Election_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Election); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Election_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Election_proto_goTypes,
		DependencyIndexes: file_Election_proto_depIdxs,
		EnumInfos:         file_Election_proto_enumTypes,
		MessageInfos:      file_Election_proto_msgTypes,
	}.Build()
	File_Election_proto = out.File
	file_Election_proto_rawDesc = nil
	file_Election_proto_goTypes = nil
	file_Election_proto_depIdxs = nil
}
