// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: ControlMessage.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ControlMessage_Command int32

const (
	ControlMessage_START          ControlMessage_Command = 0
	ControlMessage_EXIT           ControlMessage_Command = 1
	ControlMessage_EXIT_ALL       ControlMessage_Command = 2
	ControlMessage_START_ELECTION ControlMessage_Command = 3
)

// Enum value maps for ControlMessage_Command.
var (
	ControlMessage_Command_name = map[int32]string{
		0: "START",
		1: "EXIT",
		2: "EXIT_ALL",
		3: "START_ELECTION",
	}
	ControlMessage_Command_value = map[string]int32{
		"START":          0,
		"EXIT":           1,
		"EXIT_ALL":       2,
		"START_ELECTION": 3,
	}
)

func (x ControlMessage_Command) Enum() *ControlMessage_Command {
	p := new(ControlMessage_Command)
	*p = x
	return p
}

func (x ControlMessage_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessage_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_ControlMessage_proto_enumTypes[0].Descriptor()
}

func (ControlMessage_Command) Type() protoreflect.EnumType {
	return &file_ControlMessage_proto_enumTypes[0]
}

func (x ControlMessage_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessage_Command.Descriptor instead.
func (ControlMessage_Command) EnumDescriptor() ([]byte, []int) {
	return file_ControlMessage_proto_rawDescGZIP(), []int{0, 0}
}

type ControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command ControlMessage_Command `protobuf:"varint,1,opt,name=command,proto3,enum=ueb03.ControlMessage_Command" json:"command,omitempty"`
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ControlMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ControlMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_ControlMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetCommand() ControlMessage_Command {
	if x != nil {
		return x.Command
	}
	return ControlMessage_START
}

var File_ControlMessage_proto protoreflect.FileDescriptor

var file_ControlMessage_proto_rawDesc = []byte{
	0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x65, 0x62, 0x30, 0x33, 0x22, 0x8b, 0x01,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x37, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x75, 0x65, 0x62, 0x30, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x40, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x45, 0x58, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x58, 0x49,
	0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x5f, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x65, 0x6c, 0x73, 0x63,
	0x68, 0x2f, 0x76, 0x61, 0x61, 0x2f, 0x75, 0x65, 0x62, 0x30, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ControlMessage_proto_rawDescOnce sync.Once
	file_ControlMessage_proto_rawDescData = file_ControlMessage_proto_rawDesc
)

func file_ControlMessage_proto_rawDescGZIP() []byte {
	file_ControlMessage_proto_rawDescOnce.Do(func() {
		file_ControlMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ControlMessage_proto_rawDescData)
	})
	return file_ControlMessage_proto_rawDescData
}

var file_ControlMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ControlMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ControlMessage_proto_goTypes = []interface{}{
	(ControlMessage_Command)(0), // 0: ueb03.ControlMessage.Command
	(*ControlMessage)(nil),      // 1: ueb03.ControlMessage
}
var file_ControlMessage_proto_depIdxs = []int32{
	0, // 0: ueb03.ControlMessage.command:type_name -> ueb03.ControlMessage.Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ControlMessage_proto_init() }
func file_ControlMessage_proto_init() {
	if File_ControlMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ControlMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ControlMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ControlMessage_proto_goTypes,
		DependencyIndexes: file_ControlMessage_proto_depIdxs,
		EnumInfos:         file_ControlMessage_proto_enumTypes,
		MessageInfos:      file_ControlMessage_proto_msgTypes,
	}.Build()
	File_ControlMessage_proto = out.File
	file_ControlMessage_proto_rawDesc = nil
	file_ControlMessage_proto_goTypes = nil
	file_ControlMessage_proto_depIdxs = nil
}
